# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

cluster-type:
  - yarn
  - k8s

prerequisite:
  - rest-server

template-list:
  - model-proxy.yaml

start-script: start.sh
stop-script: stop.sh
delete-script: delete.sh
refresh-script: refresh.sh


deploy-rules:
  - in: pai-master
