apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webportal-ds
spec:
  selector:
    matchLabels:
      app: webportal
  template:
    metadata:
      labels:
        app: webportal
      name: webportal
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pai-master
                operator: In
                values:
                - 'true'
      containers:
      - env:
        - name: LAUNCHER_TYPE
          value: k8s
        - name: LAUNCHER_SCHEDULER
          value: hivedscheduler
        - name: REST_SERVER_URI
          value: http://10.16.0.5:9186
        - name: MARKETPLACE_API_URI
          value: https://auto-test.ltp.hpc-lucia.com:443/marketplace/api
        - name: SAVE_TEMPLATE
          value: 'false'
        - name: PROMETHEUS_URI
          value: http://10.16.0.5:9091
        - name: GRAFANA_URI
          value: http://10.16.0.5:3000
        - name: K8S_DASHBOARD_URI
          value: https://10.16.0.5:9090
        - name: K8S_API_SERVER_URI
          value: https://aks-openpai-1azggk1h.hcp.westus2.azmk8s.io:443
        - name: EXPORTER_PORT
          value: '9100'
        - name: AUTHN_METHOD
          value: OIDC
        - name: JOB_HISTORY
          value: 'true'
        - name: PROM_SCRAPE_TIME
          value: 50s
        - name: ENABLE_JOB_TRANSFER
          value: 'false'
        - name: WEBPORTAL_PLUGINS
          value: "[\n\n\n\n    {'id': 'cluster-local-storage', 'title': 'Cluster Local\
            \ Storage', 'uri': 'https://gerhut.github.io/store/cluster-local-storage-plugin.js'},\n\
            \n    {'id': 'submit-job-v2', 'title': 'Submit Job v2', 'uri': 'https://microsoft.github.io/openpaimarketplace/publish/submit-job-v2/plugin.js'},\n\
            \n    {'id': 'chat-plugin', 'title': 'Chat With Job', 'uri': 'https://zhogu.github.io/plugins/chat-plugin/main-test.js',\
            \ 'token': '1e82ef93720a4f41afc75ffda76d9039'},\n\n    {'id': 'copilot-plugin',\
            \ 'title': 'Copilot Plugin', 'uri': 'https://quge009.github.io/c-plugin/build/static/js/main.js',\
            \ 'onlyadmin': 1},\n\n\n]\n"
        image: luciaopenpai.azurecr.io/luciaopenai/webportal-new:test
        imagePullPolicy: Always
        name: webportal
        ports:
        - containerPort: 8080
          hostPort: 9286
          name: webportal
        resources:
          limits:
            memory: 512Mi
      hostNetwork: false
      hostPID: false
      imagePullSecrets:
      - name: pai-secret
