# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

service_type: "common"

port: 9093
actions-available:
- webportal-notification
- cordon-nodes
- uncordon-nodes
- reboot-nodes
- drain-nodes
- fix-nvidia-gpu-low-perf
alert-handler:
  log-level: 'info'
  port: 9095
  configured: False
alert-parser:
  configured: False
cluster-utilization:
  configured: False
job-data-recorder:
  configured: False
job-status-change-notification:
  # Max connection number to database in poller.
  configured: False
  log-level: 'info'
  db-poller-max-db-connection: 10
  db-poller-interval-second: 600
node-issue-classifier:
  configured: False
  kusto: False
node-recycler:
  configured: False
  kusto: False
  icm:
    host: prod.microsofticm.com
    crt_name: cert.pem
    crt_path: /icm/cert.pem
    key_name: key.pem
    key_path: /icm/key.pem
    connector_id: ""
    routing_id: hpclucia://AzureHPC/Lucia/TrainingPlatform
  vmss:
    client_id: ""
    vmss_ids: ""
    validation_image: bench.azurecr.io/superbench:0.11-rocm6.3
use-pylon: False
repeat-interval: '24h'
cert-expiration-checker:
  schedule: '0 0 * * *'
  alert-residual-days: 30
  cert-path: '/etc/kubernetes/ssl'
