apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-user-logs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
  volumeName: pv-user-logs
  storageClassName: azureblob-fuse-premium
  volumeMode: Filesystem