# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.


service_type: "k8s"

port-base: 17000
host-path: /mntext/clstore
job-path: /clstore
sync-interval: 600
clusters: []
clusters_hostname_regex: []
