table J-t1-AverageandMaxJobDurationTime
	lineageTag: 0ff9931b-dce8-402f-a00c-509c30ddeda9

	measure 'JDA Last Week' = ```
			
			VAR LatestWeek = [MaxWeekR]
			VAR Result = 
			    CALCULATE(
			        MAX('J-t1-AverageandMaxJobDurationTime'[Avg. Duration]),
			        'J-t1-AverageandMaxJobDurationTime'[Week] = LatestWeek
			    )
			RETURN COALESCE(Result , 0)
			```
		lineageTag: fd5626c2-d2a1-4e35-9faf-bbd08c64cfc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JDA Previous' = ```
			
			VAR LatestWeek = [MaxWeekR] - 1
			VAR Result = 
			    CALCULATE(
			        MAX('J-t1-AverageandMaxJobDurationTime'[Avg. Duration]),
			        'J-t1-AverageandMaxJobDurationTime'[Week] = LatestWeek
			    )
			RETURN COALESCE(Result, 0)
			```
		lineageTag: 93db8431-11bd-42d8-a561-666c86714561

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JDA Change' =
			
			IF(
			    [JDA Previous] > [JDA Last Week],
			    "decreased",
			    IF(
			        [JDA Previous] < [JDA Last Week],
			        "increased",
			        "unchanged"
			    )
			)
		lineageTag: a81d3293-fda6-46a7-ab8c-2c1eb96a73bd

	measure 'JDX Last Week' =
			
			VAR LatestWeek = [MaxWeekR]
			VAR Result =
			    CALCULATE(
			        MAX('J-t1-AverageandMaxJobDurationTime'[Max. Duration]),
			        'J-t1-AverageandMaxJobDurationTime'[Week] = LatestWeek
			    )
			RETURN COALESCE(Result, 0)
		lineageTag: 8465e82b-89ad-4cdb-95d1-082369d6bbac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JDX Previous' = ```
			
			VAR LatestWeek = [MaxWeekR] - 1
			VAR Result = 
			    CALCULATE(
			        MAX('J-t1-AverageandMaxJobDurationTime'[Max. Duration]),
			        'J-t1-AverageandMaxJobDurationTime'[Week] = LatestWeek
			    )
			RETURN COALESCE(Result, 0)
			```
		lineageTag: 7d4f697e-c471-4167-a75b-2b8c6f04f8d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JDX Change' =
			
			IF(
			    [JDX Previous] > [JDX Last Week],
			    "decreased",
			    IF(
			        [JDX Previous] < [JDX Last Week],
			        "increased",
			        "unchanged"
			    )
			)
		lineageTag: 13ee44e7-f675-4cfa-b113-5563c44e8b8f

	column Week
		formatString: 0
		lineageTag: 6e80ca4d-89e3-4d88-88e9-b8727120a485
		summarizeBy: none
		isNameInferred
		sourceColumn: [Week]

		annotation SummarizationSetBy = User

	column 'Avg. Duration User Stop'
		lineageTag: b7e014a6-d513-453e-8a7e-c86a647836f7
		summarizeBy: none
		isNameInferred
		sourceColumn: [Avg. Duration User Stop]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Max. Duration User Stop'
		lineageTag: 65bd4550-e809-4940-951a-783ceebc6d1f
		summarizeBy: none
		isNameInferred
		sourceColumn: [Max. Duration User Stop]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg. Duration Hardware Failure'
		lineageTag: 52b74357-7614-48b1-ada0-983510c0321e
		summarizeBy: none
		isNameInferred
		sourceColumn: [Avg. Duration Hardware Failure]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Max. Duration Hardware Failure'
		lineageTag: 890521a9-9b4a-41bd-a9cc-df9960612bf7
		summarizeBy: none
		isNameInferred
		sourceColumn: [Max. Duration Hardware Failure]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg. Duration Software Failure'
		lineageTag: 96a41e25-c3b3-4f02-9a4e-5103d5b50516
		summarizeBy: none
		isNameInferred
		sourceColumn: [Avg. Duration Software Failure]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Max. Duration Software Failure'
		lineageTag: 540e068d-5e4f-47b1-bf97-129a83f8ed63
		summarizeBy: none
		isNameInferred
		sourceColumn: [Max. Duration Software Failure]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg. Duration'
		lineageTag: 09c89f07-affa-43f2-8fcd-4ce152cb3e1c
		summarizeBy: none
		isNameInferred
		sourceColumn: [Avg. Duration]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Max. Duration'
		lineageTag: 60b4c217-2013-4c2f-a57e-565f2afe1713
		summarizeBy: none
		isNameInferred
		sourceColumn: [Max. Duration]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition J-t1-AverageandMaxJobDurationTime = calculated
		mode: import
		source =
				
				SELECTCOLUMNS(
				 'J-r0-na',
				 "Week", 'J-r0-na'[Week],
				 "Avg. Duration User Stop", 'J-r0-na'[AvgUserStop],
				 "Max. Duration User Stop", 'J-r0-na'[MaxUserStop],
				 "Avg. Duration Hardware Failure", 'J-r0-na'[AvgHardwareFailure],
				 "Max. Duration Hardware Failure", 'J-r0-na'[MaxHardwareFailure],
				 "Avg. Duration Software Failure", 'J-r0-na'[AvgSoftwareFailure],
				 "Max. Duration Software Failure", 'J-r0-na'[MaxSoftwareFailure],
				 "Avg. Duration", 'J-r0-na'[AvgDuration],
				 "Max. Duration", 'J-r0-na'[MaxDuration]
				)

	annotation PBI_Id = 8f91d3a4c91c44c0be78524ae76f88cf

