table J-t2-AverageReactionTime
	lineageTag: f4fe2ee8-c9b2-4242-b118-dc14e4872182

	measure 'JRA Last Week' =
			
			VAR LatestWeek = [MaxWeekR]
			VAR Result =
			    CALCULATE(
			        MAX('J-t2-AverageReactionTime'[Avg. Reaction Time]),
			        'J-t2-AverageReactionTime'[Week] = LatestWeek
			    )
			RETURN COALESCE(Result, 0)
		lineageTag: 3ed7e3c3-5f54-4cb9-afe0-ae223e66fbdd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JRA Previous' =
			
			VAR LatestWeek = [MaxWeekR] - 1
			VAR Result =
			    CALCULATE(
			        MAX('J-t2-AverageReactionTime'[Avg. Reaction Time]),
			        'J-t2-AverageReactionTime'[Week] = LatestWeek
			    )
			RETURN COALESCE(Result, 0)
		lineageTag: a15af3ea-b25f-4d24-8717-38fa3a7e2f8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JRA Change' =
			
			IF(
			    [JRA Previous] > [JRA Last Week],
			    "decreased",
			    IF(
			        [JRA Previous] < [JRA Last Week],
			        "increased",
			        "unchanged"
			    )
			)
		lineageTag: 1729112e-0bf9-4e22-9f63-c7ee9c3c7f1d

	column Week
		formatString: 0
		lineageTag: 8f392d59-6468-4c9d-8140-43a8830588b6
		summarizeBy: none
		isNameInferred
		sourceColumn: [Week]

		annotation SummarizationSetBy = User

	column 'User Stop'
		lineageTag: c15da6f9-54e7-493a-9408-1ed16cd8c311
		summarizeBy: none
		isNameInferred
		sourceColumn: [User Stop]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hardware Failure'
		lineageTag: d8728278-ee9e-4167-94e4-cc597836cb4a
		summarizeBy: none
		isNameInferred
		sourceColumn: [Hardware Failure]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Software Failure'
		lineageTag: daa6a5a3-7688-4dca-9ff1-483360308fa4
		summarizeBy: none
		isNameInferred
		sourceColumn: [Software Failure]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg. Reaction Time'
		lineageTag: 3abb3cdd-177c-402f-8fcf-ef2426feec3f
		summarizeBy: none
		isNameInferred
		sourceColumn: [Avg. Reaction Time]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition J-t2-AverageReactionTime = calculated
		mode: import
		source =
				
				SELECTCOLUMNS(
				 'J-r1-na',
				 "Week", 'J-r1-na'[Week],
				 "User Stop", 'J-r1-na'[AvgUserStop],
				 "Hardware Failure", 'J-r1-na'[AvgHardwareFailure],
				 "Software Failure", 'J-r1-na'[AvgSoftwareFailure],
				 "Avg. Reaction Time", 'J-r1-na'[AvgReactionTime]
				)

	annotation PBI_Id = 4f943e97a7d74f369a88d71fd96e7360

