apiVersion: v1
kind: Service
metadata:
  name: pylon-service
  namespace: default
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv4
  - IPv6
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: pylon
  type: LoadBalancer
  externalTrafficPolicy: Local