# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This tool is used to update the snapshot state in PostgreSQL for waiting jobs.
# Usage: python3 updateWaitingJob.py --connection_string "<connection_string>" [--framework_name "<framework_name>"]

import psycopg2
import argparse
import hashlib
import json
from datetime import datetime

def encode_name(name):
    def convert_name(name):
        return name.lower().replace(' ', '').replace('-', '').replace('_', '')

    if name.startswith('unknown') or '~' not in name:
        # framework is not generated by PAI
        return convert_name(name.replace('unknown', ''))
    else:
        # md5 hash
        return hashlib.md5(name.encode()).hexdigest()

def read_data_from_postgresql(connection_string, framework_name=None):
    try:
        # Connect to your postgres DBpy
        connection = psycopg2.connect(connection_string)

        # Create a cursor object
        cursor = connection.cursor()

        # Execute a query
        encoded_name = encode_name(framework_name)
        cursor.execute(f"""
            SELECT "framework"."name", "framework"."submissionTime", "framework"."snapshot", 
               "tags"."uid" AS "tags.uid", "tags"."name" AS "tags.name" 
            FROM "frameworks" AS "framework" 
            LEFT OUTER JOIN "tags" AS "tags" 
            ON "framework"."name" = "tags"."frameworkName" 
            WHERE "framework"."name" = %s
        """, (encoded_name,))

        # Retrieve query results
        records = cursor.fetchall()

        for row in records:
            return row[2]  # Return the snapshot message

    except Exception as error:
        print(f"Error reading data from PostgreSQL table: {error}")
    finally:
        if connection:
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")        

def create_update_fields(snapshot):
    completion_status = snapshot.get('status', {}).get('attemptStatus', {}).get('completionStatus', {})
    update = {
        'retries': snapshot.get('status', {}).get('retryPolicyStatus', {}).get('totalRetriedCount', 0),
        'retryDelayTime': snapshot.get('status', {}).get('retryPolicyStatus', {}).get('retryDelaySec', None),
        'platformRetries': snapshot.get('status', {}).get('retryPolicyStatus', {}).get('totalRetriedCount', 0) - snapshot.get('status', {}).get('retryPolicyStatus', {}).get('accountableRetriedCount', 0),
        'resourceRetries': 0,
        'userRetries': snapshot.get('status', {}).get('retryPolicyStatus', {}).get('accountableRetriedCount', 0),
        'creationTime': datetime.fromisoformat(snapshot.get('metadata', {}).get('creationTimestamp', '').replace('Z', '')).isoformat() + 'Z' if snapshot.get('metadata', {}).get('creationTimestamp') else None,
        'launchTime': datetime.fromisoformat(snapshot.get('status', {}).get('runTime', snapshot.get('status', {}).get('completionTime', '')).replace('Z', '')).isoformat() + 'Z' if snapshot.get('status', {}).get('runTime') or snapshot.get('status', {}).get('completionTime') else None,
        'completionTime': datetime.fromisoformat(snapshot.get('status', {}).get('completionTime', '').replace('Z', '')).isoformat() + 'Z' if snapshot.get('status', {}).get('completionTime') else None,
        'appExitCode': completion_status.get('code', None),
        'subState': snapshot.get('status', {}).get('state', None),
        'state': convert_framework_state(snapshot.get('status', {}).get('state', None), completion_status.get('code', None)),
        'snapshot': json.dumps(snapshot),
    }

    return update

def convert_framework_state(state, code):
    if state in ['AttemptCreationPending', 'AttemptCreationRequested', 'AttemptPreparing']:
        return 'WAITING'
    elif state == 'AttemptRunning':
        return 'RUNNING'
    elif state in ['AttemptDeletionPending', 'AttemptDeletionRequested', 'AttemptDeleting', 'AttemptCompleted']:
        if code in [-210, -220]:
            return 'STOPPING'
        else:
            return 'RUNNING'
    elif state == 'Completed':
        if code == 0:
            return 'SUCCEEDED'
        elif code in [-210, -220]:
            return 'STOPPED'
        else:
            return 'FAILED'
    else:
        return 'UNKNOWN'
    


def update_snapshot_in_postgresql(connection_string, framework_name, update_fields):
    try:
        connection = psycopg2.connect(connection_string)
        cursor = connection.cursor()

        cursor.execute("""
            UPDATE "frameworks"
            SET "snapshot" = %s, "retries" = %s, "retryDelayTime" = %s, "platformRetries" = %s, 
            "resourceRetries" = %s, "userRetries" = %s, "creationTime" = %s, "launchTime" = %s, 
            "completionTime" = %s, "appExitCode" = %s, "subState" = %s, "state" = %s
            WHERE "name" = %s
        """, (
            update_fields['snapshot'], update_fields['retries'], update_fields['retryDelayTime'], 
            update_fields['platformRetries'], update_fields['resourceRetries'], update_fields['userRetries'], 
            update_fields['creationTime'], update_fields['launchTime'], update_fields['completionTime'], 
            update_fields['appExitCode'], update_fields['subState'], update_fields['state'], 
            encode_name(framework_name)
        ))
        connection.commit()
    except Exception as error:
        print(f"Error updating snapshot in PostgreSQL table: {error}")
    finally:
        if connection:
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")

if __name__ == "__main__":
    #########################################################################################
    # NOTE: This script is used to update the snapshot state in PostgreSQL
    # please run it on jumpbox like openpai-000000
    #########################################################################################
    parser = argparse.ArgumentParser(description='Read data from PostgreSQL.')
    parser.add_argument('--connection_string', type=str, required=True, help='PostgreSQL connection string')
    parser.add_argument('--framework_name', type=str, required=False, help='Framework name to filter the data')
    args = parser.parse_args()
    
    result = read_data_from_postgresql(args.connection_string, args.framework_name)

    if result:
        date_str = datetime.utcnow().isoformat() + 'Z'
        state_json = {
            "state": "Completed",
            "startTime": date_str,
            "runTime": date_str,
            "transitionTime": date_str,
            "completionTime": date_str,
            "attemptStatus": {
                "completionStatus": {
                    "code": -1100,
                    "diagnostics": "Job is submitted to database, but cannot be created in ApiServer due to permanent failures.",
                    "phase": "CreateFrameworkPermanentFailed",
                    "type": {
                        "attributes": ["Permanent"],
                        "name": "Failed",
                    },
                    "id": 0,
                    "startTime": date_str,
                    "runTime": date_str,
                    "completionTime": date_str,
                },
                "taskRoleStatuses": [],
            },
            "retryPolicyStatus": {
                "retryDelaySec": None,
                "totalRetriedCount": 0,
                "accountableRetriedCount": 0,
            },
        }

        snapshot = json.loads(result)
        if snapshot.get('status', {}).get('state') == 'AttemptCreationPending':        
            snapshot['status'] = state_json
            print(json.dumps(snapshot, indent=4))
        else:
            print("The snapshot state is not AttemptCreationPending and no need to update.")
            exit(0)
        
        update = create_update_fields(snapshot)
        print(update)
        # Update the snapshot in PostgreSQL
        update_snapshot_in_postgresql(args.connection_string, args.framework_name, update)
        print("The snapshot is updated successfully.")
    else:
        print("No data was returned from PostgreSQL. Exiting.")
        exit(1)

