name: Build & Deploy All Services

permissions:
  packages: write
  contents: read

on:
  release:
    types: 
      - published
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch to run on"
        required: true
        default: "main"
      rebuildImage:
        description: "Rebuild all images"
        type: boolean
        default: true
      repushImage:
        description: "Repush all images"
        type: boolean
        default: true
      redeployService:
        description: "Redeploy all services"
        type: boolean
        default: true

env:
  TAG: ${{ github.run_number }}

jobs:
  build:
    name: Build and Deploy
    runs-on: [self-hosted, paicicd]
    timeout-minutes: 120
    environment: auto-test
    container:
      image: ubuntu:latest

    steps:
      - name: Set default parameters
        id: defaults
        run: |
          # Branch: if release use tag name else use input
          echo "branch_name=${{ github.event.inputs.branch_name || github.ref_name }}" >> $GITHUB_OUTPUT
          # default booleans if not provided
          echo "rebuildImage=${{ github.event.inputs.rebuildImage != '' && github.event.inputs.rebuildImage || true }}" >> $GITHUB_OUTPUT
          echo "repushImage=${{ github.event.inputs.repushImage != '' && github.event.inputs.repushImage || true }}" >> $GITHUB_OUTPUT
          echo "redeployService=${{ github.event.inputs.redeployService != '' && github.event.inputs.redeployService || true }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.inputs.branch_name || github.ref_name }}

      - name: Install Package
        run: |
          DEBIAN_FRONTEND=noninteractive apt install -y python3 python-is-python3 pip git unzip docker-cli ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Install python libs
        run: python -m pip install --break-system-packages pyyaml jinja2 paramiko etcd3 protobuf==3.20.3 kubernetes gitpython

      - name: Decode and unzip config file
        run: |
          echo "${{ secrets.CONFIG_FILE_B64 }}" | base64 -d > config.zip
          mkdir -p $GITHUB_WORKSPACE/config
          unzip -o config.zip -d $GITHUB_WORKSPACE/config
          ls -l $GITHUB_WORKSPACE/config

      - name: Arrange Config Files
        run: |
          rm -rf /tmp/auth-configuration
          mv $GITHUB_WORKSPACE/config/auth-configuration /tmp/
          ls -l /tmp/auth-configuration

      - name: Set the service set to build and deploy
        id: set
        run: |
          # set it to github output for next steps
          # skip alert-manager as it cannot be built by github action due to lack of access to private repo
          echo "services=cluster-configuration device-plugin cluster-local-storage job-exporter log-manager node-exporter grafana watchdog internal-storage postgresql database-controller fluentd pylon rest-server webportal copilot-chat model-proxy" >> $GITHUB_OUTPUT

      - name: Build Images of All Services
        if: ${{ steps.defaults.outputs.rebuildImage == 'true' || steps.defaults.outputs.repushImage == 'true' }}
        run: |
          $GITHUB_WORKSPACE/build/pai_build.py build \
            -c $GITHUB_WORKSPACE/config/cluster-configuration \
            -s {{ steps.set.outputs.services }}

      - name: Push Images of All Services to ACR
        if: ${{ steps.defaults.outputs.repushImage == 'true' }}
        run: |
          $GITHUB_WORKSPACE/build/pai_build.py push \
            -c $GITHUB_WORKSPACE/config/cluster-configuration \
            -s {{ steps.set.outputs.services }}

      - name: Push Images of Changed Service to GHCR
        if: ${{ steps.defaults.outputs.repushImage == 'true' }}
        run: |
          changed_services=$(echo "${{ steps.changes.outputs.folders }}" | tr ' ' '\n')
          echo "Pushing: $changed_services"
          $GITHUB_WORKSPACE/build/pai_build.py push \
            -c $GITHUB_WORKSPACE/config/cluster-configuration \
            -s {{ steps.set.outputs.services }} \
            --docker-registry ghcr.io \
            --docker-namespace ${GITHUB_REPOSITORY_OWNER} \
            --docker-username ${{ github.actor }} \
            --docker-password ${{ secrets.GITHUB_TOKEN }}

      - name: Azure CLI get credentials and deploy
        if: ${{ steps.defaults.outputs.redeployService == 'true' }}
        run: |
            az version
            az login --identity --client-id ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENT_ID }}
            az aks install-cli
            az aks get-credentials \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ secrets.KUBERNETES_CLUSTER }} \
              --overwrite-existing
            kubelogin convert-kubeconfig -l azurecli
            kubectl config use-context ${{ secrets.KUBERNETES_CLUSTER }}

            echo "${{ secrets.PAI_CLUSTER_NAME }}" > cluster_id
            echo "Stopping all pai services..."
            $GITHUB_WORKSPACE/paictl.py service stop -n {{ steps.set.outputs.services }} < cluster_id

            echo "Pushing config to cluster \"${{ secrets.PAI_CLUSTER_NAME }}\" ..."
            $GITHUB_WORKSPACE/paictl.py config push -m service -p $GITHUB_WORKSPACE/config < cluster_id

            echo "Starting to update pai..."
            $GITHUB_WORKSPACE/paictl.py service start -n {{ steps.set.outputs.services }} < cluster_id

            echo "Checking pai cluster status..."
            kubectl get pod
            kubectl get service

  test:
    name: Test rest-server
    needs: build
    runs-on: [self-hosted, paicicd]
    environment: auto-test

    steps:
      - name: Test rest-server
        run: |
          echo "Testing rest-server ${{ secrets.PAI_WEB_URL }}/rest-server/api/v2/info"
          curl ${{ secrets.PAI_WEB_URL }}/rest-server/api/v2/info
          echo "Checking virtual cluster status..."
          vc_info=$(curl -H "Authorization: Bearer ${{ secrets.PAI_WEB_TOKEN }}" -s ${{ secrets.PAI_WEB_URL }}/rest-server/api/v2/virtual-clusters)
          if [ $? -ne 0 ]; then
            echo "Failed to access virtual cluster API"
            exit 1
          fi
          echo "Virtual cluster info: $vc_info"
